container:
  image: python:slim

task:
  name: Check URLs
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: pip install requests
  test_script: python check_links
