name: Check URLs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        python,
        import os;print(os.path.abspath(os.path.dirname(__file__)));print(os.listdir())
