name: Check URLs
on: 
  push:
    branches:
    - master
  schedule:
  - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    - name: Install dependencies
      run: pip install -r tests/requirements.txt
      
    - name: Check URLs
      run: python tests/check_links
       
